name: WebHostMost Auto Login

on:
  schedule:
    # 每天的 00:30 UTC 时间执行 (北京时间 08:30)
    - cron: '30 0 * * *'
    # 每天的 20:25 UTC 时间执行 (北京时间第二天 04:25)
    - cron: '25 20 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  auto-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Perform Login, Access URL, and Execute Node.js Selector Request
        env:
          WEBHOST_USERNAME: ${{ secrets.WEBHOST_USERNAME }}
          WEBHOST_PASSWORD: ${{ secrets.WEBHOST_PASSWORD }}
          NODEJS_USER: ${{ secrets.NODEJS_USER }}
        run: |
          echo "Attempting to log in to WebHostMost..."
          
          LOGIN_RESPONSE_HTTP_CODE=$(curl -s -X POST \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -H "User-Agent: Mozilla/5.0 (GitHub Action) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36" \
            -H "Origin: https://server7.webhostmost.com:2222" \
            -H "Referer: https://server7.webhostmost.com:2222/evo/login" \
            -d "{\"username\":\"$WEBHOST_USERNAME\",\"password\":\"$WEBHOST_PASSWORD\"}" \
            --cookie-jar cookies.txt \
            -D login_headers.txt \
            --output response.json \
            --write-out "%{http_code}" \
            https://server7.webhostmost.com:2222/api/login)
          
          echo "Login HTTP Status Code: $LOGIN_RESPONSE_HTTP_CODE"
          echo "Login Response Body:"
          cat response.json
          echo ""

          if [ "$LOGIN_RESPONSE_HTTP_CODE" -ne 200 ]; then
            echo "Login failed with HTTP status code: $LOGIN_RESPONSE_HTTP_CODE"
            echo "Login Headers:"
            cat login_headers.txt
            exit 1
          fi

          if [ ! -s response.json ]; then
            echo "Login response body is empty or invalid."
            exit 1
          fi
          
          SESSION_ID_FROM_BODY=$(jq -r '.sessionID' response.json)
          LOGIN_URL=$(jq -r '.loginURL' response.json)
          
          SESSION_VALUE_FROM_HEADER=$(grep -i '^Set-Cookie: session=' login_headers.txt | sed -E 's/.*session=([^;]+);.*/\1/' | head -n 1)

          if [ -z "$SESSION_VALUE_FROM_HEADER" ]; then
            echo "Failed to extract session from login headers."
            echo "Login Headers Content:"
            cat login_headers.txt
          else
            echo "Extracted session from header for new request: $SESSION_VALUE_FROM_HEADER"
          fi
          
          if [ "$SESSION_ID_FROM_BODY" = "null" ] || [ -z "$SESSION_ID_FROM_BODY" ] || [ "$LOGIN_URL" = "null" ] || [ -z "$LOGIN_URL" ]; then
            echo "Login failed: Could not extract sessionID (from body) or loginURL from response."
            echo "SessionID (from body): $SESSION_ID_FROM_BODY"
            echo "LoginURL: $LOGIN_URL"
            exit 1
          else
            echo "Login successful (extracted from body)!"
            echo "SessionID (from body): $SESSION_ID_FROM_BODY"
            echo "LoginURL: $LOGIN_URL"
            echo "Attempting to access loginURL..."
            ACCESS_RESPONSE_HTTP_CODE=$(curl -s -L \
              -b cookies.txt \
              -H "User-Agent: Mozilla/5.0 (GitHub Action) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36" \
              -H "Referer: https://server7.webhostmost.com:2222/api/login" \
              "$LOGIN_URL" \
              -o /dev/null \
              -w "%{http_code}")
            
            echo "Access loginURL HTTP Status Code: $ACCESS_RESPONSE_HTTP_CODE"
            if [[ "$ACCESS_RESPONSE_HTTP_CODE" -ge 200 && "$ACCESS_RESPONSE_HTTP_CODE" -lt 400 ]]; then
              echo "Successfully accessed loginURL."
            else
              echo "Failed to access loginURL. Status code: $ACCESS_RESPONSE_HTTP_CODE"
            fi
          fi

          echo ""
          echo "Attempting to execute Node.js Selector request..."

          if [ -z "$NODEJS_USER" ]; then
            echo "Error: NODEJS_USER secret is not set. Skipping Node.js Selector request."
          elif [ -z "$SESSION_VALUE_FROM_HEADER" ]; then
            echo "Error: Session from header is missing for Node.js Selector request. Skipping request."
          else
            POST_DATA="command=cloudlinux-selector&method=get&params[interpreter]=nodejs&params[user]=$NODEJS_USER&csrftoken=1"
            
            echo "Executing Node.js Selector POST request..."
            curl -s -X POST \
              -H "Host: server7.webhostmost.com:2222" \
              -H "Cookie: csrftoken=1; session=$SESSION_VALUE_FROM_HEADER" \
              -H "X-Csrftoken: 1" \
              -H "Content-Type: application/x-www-form-urlencoded" \
              -d "$POST_DATA" \
              -o nodejs_selector_response.json \
              https://server7.webhostmost.com:2222/CMD_PLUGINS/nodejs_selector/index.raw?c=send-request
            
            echo "Node.js Selector Request executed."
            if [ -s nodejs_selector_response.json ]; then
              echo "Response Body (saved to nodejs_selector_response.json):"
              cat nodejs_selector_response.json
              echo ""

              # MODIFIED LINE BELOW
              DOMAIN_VALUE=$(jq -r --arg target_user "$NODEJS_USER" '([.available_versions[]?.users?[$target_user]?.applications?[]?.domain?] | map(select(type=="string")) | .[0]) // ""' nodejs_selector_response.json)

              if [ -n "$DOMAIN_VALUE" ] && [ "$DOMAIN_VALUE" != "null" ]; then # Check against empty string or "null" string
                echo "Successfully extracted domain value:"
                echo "$DOMAIN_VALUE"
              else
                echo "Could not extract 'domain' value or it was null/empty from Node.js Selector response."
                echo "Queried for user: $NODEJS_USER"
              fi
            else
              echo "Node.js Selector request did not produce a response body or the response was empty."
            fi
          fi
          
          echo "Cleaning up temporary files..."
          rm -f response.json cookies.txt login_headers.txt nodejs_selector_response.json
